-- NOTE: The 'clients' table already exists with UUID primary keys (based on error 42804).
-- We do not recreate clients here.

-- 1. Create Production Projects (using UUID to match system standards)
CREATE TABLE IF NOT EXISTS public.production_projects (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id uuid REFERENCES public.clients(id) ON DELETE SET NULL,
    title text,
    type text,
    status text,
    start_date timestamptz,
    deadline timestamptz,
    responsible_id uuid REFERENCES auth.users(id),
    team_ids uuid[],
    progress integer DEFAULT 0,
    budget numeric,
    actual_cost numeric,
    notes text,
    folder_url text
);

ALTER TABLE public.production_projects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for authenticated users on projects" ON public.production_projects;
CREATE POLICY "Enable all access for authenticated users on projects" ON public.production_projects
    FOR ALL USING (auth.role() = 'authenticated');


-- 2. Create Assets table (Foreign keys must be UUID)
CREATE TABLE IF NOT EXISTS public.assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    url text NOT NULL,
    thumbnail_url text,
    type text NOT NULL CHECK (type IN ('photo', 'video', 'design')),
    project_id uuid REFERENCES public.production_projects(id) ON DELETE SET NULL, -- UUID
    client_id uuid REFERENCES public.clients(id) ON DELETE SET NULL, -- UUID
    tags text[] DEFAULT '{}',
    file_info jsonb DEFAULT '{}'::jsonb,
    usage_rights jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_assets_auth" ON public.assets;
CREATE POLICY "public_assets_auth" ON public.assets
    FOR ALL USING (auth.role() = 'authenticated');
    
DROP POLICY IF EXISTS "public_assets_read_anon" ON public.assets;
CREATE POLICY "public_assets_read_anon" ON public.assets
    FOR SELECT USING (true);


-- 3. Create Deliveries table
CREATE TABLE IF NOT EXISTS public.deliveries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    recipient_email text NOT NULL,
    share_link_token text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'Enviado',
    expires_at timestamptz,
    project_id uuid REFERENCES public.production_projects(id) ON DELETE SET NULL, -- UUID
    created_by uuid REFERENCES auth.users(id),
    views integer DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_deliveries_auth" ON public.deliveries;
CREATE POLICY "public_deliveries_auth" ON public.deliveries
    FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "public_deliveries_anon" ON public.deliveries;
CREATE POLICY "public_deliveries_anon" ON public.deliveries
    FOR SELECT TO anon USING (true);


-- 4. Create Delivery Items table
CREATE TABLE IF NOT EXISTS public.delivery_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    delivery_id uuid REFERENCES public.deliveries(id) ON DELETE CASCADE,
    asset_id bigint REFERENCES public.assets(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.delivery_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_delivery_items_auth" ON public.delivery_items;
CREATE POLICY "public_delivery_items_auth" ON public.delivery_items
    FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "public_delivery_items_anon" ON public.delivery_items;
CREATE POLICY "public_delivery_items_anon" ON public.delivery_items
    FOR SELECT TO anon USING (true);
